### ISSUE TITLE
### 線を伸ばすアニメーション

### ISSUE THREAD

**Issue by ShogoHirasawa** [ShogoHirasawa/Mapbox_rootmap#4]
ちあきさんから[貰った資料](https://docs.google.com/document/d/1g9Irx8ygps9C9elXo7BnSICX1hCuj-k-wrPvrRFFMK8/edit)に書いてあった線のアニメーションをもう少し具体的に聞きたい。
レファレンスがあれば共有してほしい

**Comment by chiakiyamaga** [comment]
アニメーションはストーリーテリング内では厳しそうな気がしてきたので無しで大丈夫です！
ご放念ください！

**Comment by ShogoHirasawa** [comment]
かしこまりました！
ありがとうございますm(_ _)m
